name: Rust

on:
  push:
    branches: [ "develop", "github" ]
  pull_request:
    branches: [ "develop", "github" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: redhat/ubi8:latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare cargo
      run: dnf install -y rust-toolset openssl-devel
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: dist-rust-build
        path: |
          target/release/ocipkg
